### ISSUE TITLE
[FIRRTL] Make Grand Central YAML Output use Block Scalar Output

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#2846]
Currently, Grand Central will output multiline YAML description strings as one line, e.g., `"foo\nbar\baz"`.  However, the LLVM YAML library has support for instead emitting this in "block scala" format: https://llvm.org/docs/YamlIO.html#block-scalars. Change FIRRTL's Grand Central pass to do block scalar output of description strings for better readability of the output YAML.

Once implemented, this will change [this test](https://github.com/llvm/circt/blob/69f8394fb59d88ce976754352df020ecdeac743f/test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir#L363) from:

```yaml
- name: sub_vecOfBundle
  description: "a vector of a bundle in the submodule with a\nmultiline comment"
  dimensions: [ 2 ]
```

To something like:

```yaml
- name: sub_vecOfBundle
  description: |-
    a vector of a bundle in the submodule with a
    multiline comment
  dimensions: [ 2 ]
```

This should be implemented using LLVM's YAML library support for block scalars, i.e., this likely requires implementing  `BlockScalarTraits<X>` for all `X` that have a description that should have multiline output.
